spring:
  application:
    name: Gateway-Server
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:41193/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
