spring:
  datasource:
    url: jdbc:postgresql://localhost:49155/postgres
    username: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
server:
  port: 9091
  servlet:
    context-path: /auth

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:41193/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost